version: "3.8"
services:
  nacos-mysql:
    image: docker.io/arm64v8/mysql:8.0
    container_name: nacos-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nacos-config
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    volumes:
      - ./nacos-mysql-init-schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  nacos-register-service:
    image: docker.io/nacos/nacos-server:v2.2.0
    container_name: nacos-register-service
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=nacos-mysql
      - MYSQL_SERVICE_DB_NAME=nacos-config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nacos-register-service:8848/nacos/actuator/health" ]
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
  gateway-service:
    image: docker.io/redxiiikk/learn-gateway-service:1.0.0
    container_name: gateway-service
    environment:
      - APPLICATION_SERVER_PORT=8080
      - NACOS_SERVER_ADDR=nacos-register-service:8848
      - NACOS_NAMESPACE=public
      - NACOS_GROUP=com.github.redxiiikk.learn.gateway-dispatch
    ports:
      - "8080:8080"
      - "5005:5005"
  hello-service-baseline:
    image: docker.io/redxiiikk/learn-hello-service:1.0.0
    container_name: hello-service-baseline
    environment:
      - APPLICATION_SERVER_PORT=8080
      - NACOS_SERVER_ADDR=nacos-register-service:8848
      - NACOS_NAMESPACE=public
      - NACOS_GROUP=com.github.redxiiikk.learn.gateway-dispatch
      - ISOLATION=baseline
  hello-service-dev:
    image: docker.io/redxiiikk/learn-hello-service:1.0.0
    container_name: hello-service-dev
    environment:
      - APPLICATION_SERVER_PORT=8080
      - NACOS_SERVER_ADDR=nacos-register-service:8848
      - NACOS_NAMESPACE=public
      - NACOS_GROUP=com.github.redxiiikk.learn.gateway-dispatch
      - ISOLATION=dev-redxiiikk