server:
  port: ${APPLICATION_SERVER_PORT:8080}
spring:
  application:
    name: hello-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        metadata:
          ISOLATION: ${ISOLATION:baseline}
