name: Build and Publish
on:
  pull_request:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Check with Gradle
        run: ./gradlew check --no-daemon
